# Site settings
title:          Steven Tucci
description:    "Personal Site"
url:            "https://tucci.github.io/tuccico5/"

# Author
author:
  name:         Steven Tucci
  email:        tuccisteven@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
